### PR TITLE
helm: sshd: add SYS_CHROOT capability

### PR DESCRIPTION
**Pull request by Frankkkkk**
When rsyncing via using SSH, the server chroots itself on every incoming
connection.

If the underlying CRI doesn't allow the chroot capability, the
following error is raised:

```
chroot("/var/empty"): Operation not permitted [preauth]
```
which results in a `pv-migrate` migration failure.

CRI-O, one popular Container Runtime Interface, does not add the
`SYS_CHROOT` capability by default since 1.18.

This commit fixes that.

Signed-off-by: Frank Villaro-Dixon <frank.villaro@infomaniak.com>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by utkuozdemir** [comment]
Nice, thank you. Can you bump the chart version to 0.2.2 and do `helm package`, put it under `internal/migrator` and fix the `embed` reference here: https://github.com/utkuozdemir/pv-migrate/blob/master/internal/migrator/migrator.go#L19

Thank you

**Comment by Frankkkkk** [comment]
> Nice, thank you. Can you bump the chart version to 0.2.2 and do `helm package`, put it under `internal/migrator` and fix the `embed` reference here: https://github.com/utkuozdemir/pv-migrate/blob/master/internal/migrator/migrator.go#L19
> 
> Thank you

Indeed, I forgot.

I'll edit #153 too to use `helm package` which is way nicer than a `tar` command :P

**Comment by utkuozdemir** [comment]
> > Nice, thank you. Can you bump the chart version to 0.2.2 and do `helm package`, put it under `internal/migrator` and fix the `embed` reference here: https://github.com/utkuozdemir/pv-migrate/blob/master/internal/migrator/migrator.go#L19
> > Thank you
> 
> Indeed, I forgot.
> 
> I'll edit #153 too to use `helm package` which is way nicer than a `tar` command :P

Awesome, you can also add to the instructions to bump the version and update it in the code :)

**Comment by Frankkkkk** [comment]
It should be all good :+1: Don't hesitate if you see some more fuckups on my part ^^
Cheers and thank you too for you reactivity

**Comment by utkuozdemir** [comment]
And it's in the new release 🎉

**Comment by Frankkkkk** [comment]
Nice, thanks @utkuozdemir  !

**Pull request merged**
