### PR TITLE
Add helm rsync.fixPrivateKeyPerms option (#246)

### PR DESCRIPTION
**Pull request by alex-vmw**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by utkuozdemir** [comment]
Thank you for the contribution!

**Comment by alex-vmw** [comment]
@utkuozdemir Is there any possible way that you can release version 1.4.1 with this fix?

**Comment by utkuozdemir** [comment]
Sure - it's gonna be `1.5.0` since it is a feature (semver). It's being released atm.

**Comment by alex-vmw** [comment]
@utkuozdemir I am so sorry, but I am testing 1.5.0 and I realized that there is an issue with the Helm white space formatting in my change. :( Since I have `-` before the `if` it removes all white space including the new line and renders as below:
```
period=5chmod 400 /root/.ssh/id_ed25519
```
I am not sure if there is a way to re-call 1.5.0 or do you want me to submit a fix on top of 1.5.0?

**Comment by utkuozdemir** [comment]
No problem at all, you can just open another PR to the main branch and we make the hotfix release v1.5.1.

Let's just also change one of the simple integration tests to set this flag to true, so we'd be sure that it works when passed.

**Pull request merged**
