### PR TITLE
Feat/sync between different clusters

### PR DESCRIPTION
**Pull request by cgroschupp**
allow migration between different clusters. Because this requires a external service, it is import to replace the hard coded ssh keys: see at https://github.com/cgroschupp/pv-migrate/pull/1

### CODE REVIEW

**Comment by cgroschupp** [comment]
@utkuozdemir What do you think?

**Comment by utkuozdemir** [comment]
Thank you for the PR. It is a good feature to add. I'll try to have a look ASAP and let you know.

**Comment by cgroschupp** [comment]
@utkuozdemir Did you have time to look at it?

**Comment by utkuozdemir** [comment]
@cgroschupp Sorry that it took forever for me to have a look. I had other priorities so couldn't get to that.
I have cloned your branch just couple of days ago to have a look.
Looks good overall, but I'll have a deeper review in the next week or so.
Currently, I have faced some issues with the makefile. I recommend deleting it for now, so it can be added in a separate PR. Let's keep the scope of this PR to add multi cluster support (+ switch to go modules).

**Comment by utkuozdemir** [comment]
@cgroschupp I have just tried the transfer between different clusters.

- If the cluster does not have an external load balancer (which is a very common scenario), the application waits indefinitely (LB stays pending).
It needs to time out after a while, like after 5 minutes or so by default. It also needs to be configurable with a flag like `--lb-public-ip-wait-seconds`. When it times out, it should clean up the resources it created but terminate with a non-zero exit code.

- I liked the `readOnly` mounting idea. I think it should not be optional but should always the case for the source PVC. Together with this, `sourceReadOnly` flag can be removed (which does not follow the naming convention with other flags anyways).

**Comment by cgroschupp** [comment]
@utkuozdemir done

**Comment by utkuozdemir** [comment]
@cgroschupp 
I have pushed your changes together with my refactor (idk how it happened lol :D). See the commits on the master branch: https://github.com/utkuozdemir/pv-migrate/commits/master

Therefore I am closing this PR. Thank you for your contribution. I also sent to an invite to be a collaborator.

**Pull request closed without merging**
